#include: package:lints/recommended.yaml
#include: package:pedantic/analysis_options.yaml
include: package:analysis_options/analysis_options.yaml
analyzer:
  exclude: [build/**]

  language:
    strict-casts: true
    strict-raw-types: true


  strong-mode:
    implicit-casts: false
    implicit-dynamic: false



linter:
  rules:
  #public_member_api_docs: false
    - cancel_subscriptions
    - always_declare_return_types
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_final_in_for_each
    - prefer_single_quotes
    - always_use_package_imports


dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
